/** Canonical desktop release build (0.3.0-dev.4 spec 2–4, 50–52).
 *
 * One command: clean stale frontend artifacts → build frontend (identity
 * generated by prebuild) → verify version parity → build Tauri → package
 * (portable + installer + checksums + manifest + tester README) → verify the
 * packaged frontend carries the expected build identity.
 *
 * Usage: npm run desktop:release
 */
import { execSync } from "node:child_process";
import { existsSync, rmSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const step = (name) => console.log(`\n=== ${name} ===`);
const run = (cmd, opts = {}) => execSync(cmd, { stdio: "inherit", cwd: root, ...opts });

const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf-8"));
const version = pkg.version;

step("clean stale frontend artifacts");
for (const p of ["dist", "node_modules/.vite"]) {
  if (existsSync(join(root, p))) {
    rmSync(join(root, p), { recursive: true, force: true });
    console.log("removed", p);
  }
}

step("build frontend (prebuild generates build identity)");
run("npm run build");

step("verify version parity + build identity");
run("node scripts/set-version.mjs"); // no arg = parity check across 4 surfaces
const identity = readFileSync(join(root, "src", "build-identity.ts"), "utf-8");
const commit = identity.match(/BUILD_COMMIT = "([^"]+)"/)?.[1];
const bundleId = identity.match(/FRONTEND_BUILD_ID = "([^"]+)"/)?.[1];
if (!commit || commit === "unknown") throw new Error("build identity missing commit");
console.log(`identity ok — commit ${commit}, frontend build ${bundleId}`);

// the built dist must embed the same identity
const distAssets = readdirRecursive(join(root, "dist")).filter((f) => f.endsWith(".js"));
const embedded = distAssets.some((f) => readFileSync(f, "utf-8").includes(commit));
if (!embedded) throw new Error("dist does not embed the build identity — stale bundle");
console.log("dist embeds identity ✓");

step("build Tauri desktop");
run("npx tauri build");

step("package release artifacts");
run("python scripts/package-release.py");

step("packaged");
console.log(`Wildlife Incident Handoff ${version} — commit ${commit}, frontend ${bundleId}`);
console.log("artifacts in release/desktop (checksums + manifest + INSTALL.txt)");

function readdirRecursive(dir) {
  const out = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...readdirRecursive(p));
    else out.push(p);
  }
  return out;
}
