/**
 * release:all — ONE source-of-truth release pipeline (0.3.0-dev.5, Part XIX).
 *
 * From the CURRENT commit it produces:
 *   - frontend build (identity generated by prebuild)
 *   - web package (dist, PWA — deployable as-is)
 *   - desktop package (portable + installer via desktop:release)
 *   - release/current/manifest.json with version/commit/frontend build id
 *   - release/current/web.zip + checksums
 *
 * Parity contract: if any step's recorded identity disagrees with the source
 * commit, the release FAILS (spec 106).
 *
 * Usage: npm run release:all
 */
import { execSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
  copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync,
} from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const step = (name) => console.log(`\n=== ${name} ===`);
const run = (cmd) => execSync(cmd, { stdio: "inherit", cwd: root });

const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf-8"));
const version = pkg.version;

step("tests");
run("npm test -- --silent");

step("typecheck");
run("npm run typecheck");

step("frontend build (shared by web + desktop)");
run("npm run build");

step("verify identity");
const identity = readFileSync(join(root, "src", "build-identity.ts"), "utf-8");
const commit = identity.match(/BUILD_COMMIT = "([^"]+)"/)?.[1];
const frontendBuildId = identity.match(/FRONTEND_BUILD_ID = "([^"]+)"/)?.[1];
const buildTime = identity.match(/BUILD_TIME = "([^"]+)"/)?.[1];
if (!commit || commit === "unknown") throw new Error("release:all — build identity has no commit");
if (!frontendBuildId || frontendBuildId === "dev") throw new Error("release:all — frontend build id missing");
console.log(`identity: version ${version} · commit ${commit} · frontend ${frontendBuildId}`);

step("desktop package (portable + installer + parity gates)");
run("npm run desktop:release");

// The desktop:release pipeline rebuilds the frontend and may refresh the
// identity; re-read it so the manifest records exactly what was packaged.
const identity2 = readFileSync(join(root, "src", "build-identity.ts"), "utf-8");
const commit2 = identity2.match(/BUILD_COMMIT = "([^"]+)"/)?.[1];
const frontendBuildId2 = identity2.match(/FRONTEND_BUILD_ID = "([^"]+)"/)?.[1];
if (commit2 !== commit || frontendBuildId2 !== frontendBuildId) {
  throw new Error(`release:all — identity drift across pipeline (${commit}/${frontendBuildId} vs ${commit2}/${frontendBuildId2}); FAIL per spec 106`);
}

step("web package");
const releaseCurrent = join(root, "release", "current");
mkdirSync(releaseCurrent, { recursive: true });
const webZip = join(releaseCurrent, "web.zip");
if (existsSync(webZip)) rmSync(webZip);
run(`powershell -NoProfile -Command "Compress-Archive -Path 'dist/*' -DestinationPath 'release/current/web.zip' -Force"`);

step("verify packaged desktop identity matches source commit");
const manifestSrc = join(root, "release", "desktop", "release-manifest.json");
const desktopManifest = JSON.parse(readFileSync(manifestSrc, "utf-8"));
const desktopCommit = desktopManifest.commit ?? desktopManifest.commitShort;
if (desktopCommit && desktopCommit !== commit) {
  throw new Error(`release:all — desktop packaged from commit ${desktopCommit}, source is ${commit}; FAIL per spec 106`);
}

step("release manifest");
const portable = join(root, "release", "desktop", `Wildlife-Incident-Handoff-Portable-${version}.exe`);
const installer = join(root, "release", "desktop", `Wildlife-Incident-Handoff-Setup-${version}.exe`);
for (const f of [portable, installer]) {
  if (!existsSync(f)) throw new Error(`release:all — expected artifact missing: ${f}`);
}
copyFileSync(portable, join(releaseCurrent, `Wildlife-Incident-Handoff-Portable-${version}.exe`));
copyFileSync(installer, join(releaseCurrent, `Wildlife-Incident-Handoff-Setup-${version}.exe`));

const sha256 = (p) => createHash("sha256").update(readFileSync(p)).digest("hex");
const manifest = {
  version,
  commit,
  frontendBuildId,
  desktopBuildId: frontendBuildId,
  webBuildId: frontendBuildId,
  buildTime,
  generatedAt: new Date().toISOString(),
  portable: `Wildlife-Incident-Handoff-Portable-${version}.exe`,
  installer: `Wildlife-Incident-Handoff-Setup-${version}.exe`,
  web: "web.zip",
  sizeBytes: {
    portable: statSync(portable).size,
    installer: statSync(installer).size,
    webZip: statSync(webZip).size,
  },
};
writeFileSync(join(releaseCurrent, "manifest.json"), JSON.stringify(manifest, null, 2));

step("checksums");
writeFileSync(
  join(releaseCurrent, "checksums.sha256"),
  ["manifest.json", manifest.portable, manifest.installer, "web.zip"]
    .map((f) => `${sha256(join(releaseCurrent, f))}  ${f}`)
    .join("\n") + "\n",
);

console.log(`\nrelease:all OK — ${version} @ ${commit}`);
console.log(`current artifacts: ${releaseCurrent}`);
