// Wildlife Incident Handoff Launcher (0.3.0-dev.7).
//
// Native launcher for the local project/development workspace. It answers:
// which build do I open, is the desktop build stale, do I need to compile, is
// there an update, which version/commit am I launching?
//
// Design contract:
// - ONE freshness model: the desktop build is CURRENT when the release
//   manifest commit matches source HEAD, or when HEAD has only advanced by
//   commits that do not touch build inputs (docs/chore). Uncommitted build
//   inputs mean "Source has unbuilt changes", never a silent pretend-fresh.
//   Generated build-identity files are excluded from that dirty test (they are
//   rewritten by the pipeline itself).
// - release/current/manifest.json is the source of truth for artifact paths.
//   Filenames are resolved relative to the manifest directory; fallback
//   discovery scans release/current only (never archived builds).
// - "Check for updates" is read-only: it reports no-remote / offline /
//   remote-error / auth / up-to-date / available / dirty-tree and NEVER pulls.
// - Build output is streamed (stage timeline from the pipeline's `=== step ===`
//   markers); no visible terminal window.
// - Theme is read from the shared visual config (launcher-theme.json) written
//   by the application; Forest Night is the fallback.

#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use std::os::windows::process::CommandExt;

use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::Mutex;
use tauri::State;

const CREATE_NO_WINDOW: u32 = 0x0800_0000;

/// Paths that change what a desktop/web build produces. A diff in only
/// docs/changelog/release-commits does NOT make the packaged build stale.
const BUILD_INPUTS: &[&str] = &[
    "src",
    "src-tauri",
    "public",
    "index.html",
    "vite.config.ts",
    "tsconfig.json",
    "package.json",
    "package-lock.json",
    "scripts",
];
/// Generated by the pipeline at build time; its modified state in the working
/// tree is not "unbuilt changes".
const GENERATED_DIRTY_EXEMPT: &[&str] = &["src/build-identity.ts"];

#[derive(Clone)]
struct BuildState {
    running: std::sync::Arc<Mutex<bool>>,
    lines: std::sync::Arc<Mutex<Vec<String>>>,
    stage: std::sync::Arc<Mutex<String>>,
    stage_index: std::sync::Arc<Mutex<usize>>,
    done: std::sync::Arc<Mutex<Option<bool>>>,
    last_ok: std::sync::Arc<Mutex<Option<bool>>>,
}

impl BuildState {
    fn new() -> Self {
        BuildState {
            running: std::sync::Arc::new(Mutex::new(false)),
            lines: std::sync::Arc::new(Mutex::new(Vec::new())),
            stage: std::sync::Arc::new(Mutex::new(String::new())),
            stage_index: std::sync::Arc::new(Mutex::new(0)),
            done: std::sync::Arc::new(Mutex::new(None)),
            last_ok: std::sync::Arc::new(Mutex::new(None)),
        }
    }
}

/// Canonical build stages shown as a timeline (index into UI list).
const STAGES: &[&str] = &[
    "Preparing",
    "Testing",
    "Building frontend",
    "Building desktop",
    "Packaging",
    "Verifying",
    "Updating release/current",
    "Ready.",
];

/// Map a pipeline `=== step ===` heading (or notable log text) to a canonical
/// stage index.
fn stage_for_step(step: &str) -> Option<usize> {
    let s = step.to_lowercase();
    if s.contains("clean") || s.contains("prepar") {
        Some(0)
    } else if s == "tests" || s.contains("test") {
        Some(1)
    } else if s.contains("frontend") && !s.contains("verify") {
        Some(2)
    } else if s.contains("desktop") || s.contains("tauri") {
        Some(3)
    } else if s.contains("packag") || s.contains("web package") {
        Some(4)
    } else if s.contains("verif") || s.contains("parity") || s.contains("identity") {
        Some(5)
    } else if s.contains("manifest") || s.contains("checksum") || s.contains("release/current") {
        Some(6)
    } else {
        None
    }
}

fn main() {
    tauri::Builder::default()
        .manage(BuildState::new())
        .invoke_handler(tauri::generate_handler![
            get_identity,
            launch_app,
            launch_previous,
            launch_web,
            build_app,
            get_build_status,
            check_updates,
            get_theme,
            set_theme,
            get_diagnostics,
            get_prefs,
            set_prefs,
            check_release_update,
            open_release_folder,
            open_logs_folder,
        ])
        .run(tauri::generate_context!())
        .expect("launcher failed to start");
}

/// Locate the project workspace root: the nearest ancestor (starting from the
/// launcher's own directory) that has package.json + src-tauri + src.
fn find_root() -> Option<PathBuf> {
    let start = std::env::current_exe().ok()?.parent().map(|p| p.to_path_buf())?;
    let mut dir: Option<&Path> = Some(start.as_path());
    while let Some(d) = dir {
        if d.join("package.json").is_file() && d.join("src-tauri").is_dir() && d.join("src").is_dir() {
            return Some(d.to_path_buf());
        }
        dir = d.parent();
    }
    None
}

fn read_version(root: &Path) -> Option<String> {
    let text = std::fs::read_to_string(root.join("package.json")).ok()?;
    let v: serde_json::Value = serde_json::from_str(&text).ok()?;
    v.get("version")?.as_str().map(String::from)
}

fn git(root: &Path, args: &[&str]) -> Option<String> {
    let out = Command::new("git")
        .args(args)
        .current_dir(root)
        .creation_flags(CREATE_NO_WINDOW)
        .output()
        .ok()?;
    let s = String::from_utf8_lossy(&out.stdout).trim().to_string();
    if out.status.success() && !s.is_empty() {
        Some(s)
    } else {
        None
    }
}

/// Uncommitted changes (porcelain), with generated files exempted.
fn dirty_paths(root: &Path) -> Vec<String> {
    let raw = match git(root, &["status", "--porcelain"]) {
        Some(s) if !s.is_empty() => s,
        _ => return Vec::new(),
    };
    raw.lines()
        .filter_map(|l| {
            if l.len() < 4 {
                return None;
            }
            let p = l[3..].trim().trim_matches('"').replace('\\', "/");
            Some(p)
        })
        .filter(|p| !GENERATED_DIRTY_EXEMPT.iter().any(|g| p == *g || p.starts_with(&format!("{}/", *g))))
        .collect()
}

fn dirty_build_inputs(root: &Path) -> Vec<String> {
    dirty_paths(root)
        .into_iter()
        .filter(|p| BUILD_INPUTS.iter().any(|b| p == *b || p.starts_with(&format!("{}/", *b))))
        .collect()
}

fn build_inputs_changed_between(root: &Path, from_commit: &str, to_head: &str) -> Vec<String> {
    let diff = match git(root, &["diff", "--name-only", &format!("{}..{}", from_commit, to_head)]) {
        Some(s) => s,
        None => return Vec::new(),
    };
    diff.lines()
        .map(|p| p.replace('\\', "/"))
        .filter(|p| BUILD_INPUTS.iter().any(|b| p == *b || p.starts_with(&format!("{}/", *b))))
        .filter(|p| !GENERATED_DIRTY_EXEMPT.iter().any(|g| p == *g || p.starts_with(&format!("{}/", *g))))
        .collect()
}

/// Resolve a manifest artifact reference to an existing file. Bare filenames
/// are relative to the manifest's directory (release/current) — this was the
/// root cause of "Desktop executable not found" in dev.6.
fn resolve_artifact(current_dir: &Path, reference: &str) -> Option<PathBuf> {
    let p = PathBuf::from(reference);
    if p.is_absolute() {
        return if p.is_file() { Some(p) } else { None };
    }
    let joined = current_dir.join(&p);
    if joined.is_file() {
        return Some(joined);
    }
    // Last resort: the workspace release/current dir of a moved manifest copy.
    None
}

fn portable_exe_fallback(root: &Path) -> Option<PathBuf> {
    // Safe fallback: newest portable EXE in release/current ONLY (never
    // archived builds elsewhere).
    let dir = root.join("release").join("current");
    let mut best: Option<(std::time::SystemTime, PathBuf, String)> = None;
    for e in std::fs::read_dir(&dir).ok()?.flatten() {
        let p = e.path();
        let name = p.file_name()?.to_string_lossy().to_string();
        if name.starts_with("Wildlife-Incident-Handoff-Portable-") && name.ends_with(".exe") {
            let modified = e.metadata().ok()?.modified().ok()?;
            let version = name
                .trim_start_matches("Wildlife-Incident-Handoff-Portable-")
                .trim_end_matches(".exe")
                .to_string();
            if best.as_ref().map(|(t, _, _)| modified > *t).unwrap_or(true) {
                best = Some((modified, p, version));
            }
        }
    }
    best.map(|(_, p, _)| p)
}

#[derive(Serialize, Clone)]
#[serde(rename_all = "camelCase")]
struct DesktopInfo {
    version: String,
    commit: String,
    frontend_build_id: String,
    web_build_id: String,
    /// Absolute path of the launchable portable EXE (resolved from the
    /// manifest), if one exists on disk.
    exe: Option<String>,
    exe_exists: bool,
    manifest_ok: bool,
}

#[derive(Serialize, Clone)]
#[serde(rename_all = "camelCase")]
struct PreviousBuild {
    version: String,
    exe: String,
}

fn previous_verified(root: &Path, current_version: &str) -> Option<PreviousBuild> {
    // Newest Portable EXE in release/current whose version differs from the
    // current one; the manifest + checksums in that directory cover it.
    let dir = root.join("release").join("current");
    let mut best: Option<(std::time::SystemTime, PathBuf, String)> = None;
    for e in std::fs::read_dir(&dir).ok()?.flatten() {
        let p = e.path();
        let name = p.file_name()?.to_string_lossy().to_string();
        if name.starts_with("Wildlife-Incident-Handoff-Portable-") && name.ends_with(".exe") {
            let version = name
                .trim_start_matches("Wildlife-Incident-Handoff-Portable-")
                .trim_end_matches(".exe")
                .to_string();
            if version == current_version {
                continue;
            }
            let modified = e.metadata().ok()?.modified().ok()?;
            if best.as_ref().map(|(t, _, _)| modified > *t).unwrap_or(true) {
                best = Some((modified, p, version));
            }
        }
    }
    best.map(|(_, p, v)| PreviousBuild { version: v, exe: p.to_string_lossy().to_string() })
}

/// Freshness verdict for the desktop build.
#[derive(Serialize, Clone, PartialEq)]
#[serde(rename_all = "kebab-case")]
enum Freshness {
    Current,
    SourceChanged,
    SourceDirty,
    VersionMismatch,
    DesktopMissing,
    NotGit,
}

#[derive(Serialize, Clone)]
#[serde(rename_all = "camelCase")]
struct Identity {
    root: String,
    version: String,
    commit: String,
    git_dirty: bool,
    dirty_build_inputs: Vec<String>,
    desktop: Option<DesktopInfo>,
    previous: Option<PreviousBuild>,
    freshness: Freshness,
    freshness_detail: String,
}

fn desktop_release(root: &Path) -> Option<DesktopInfo> {
    let manifest_path = root.join("release").join("current").join("manifest.json");
    let current_dir = manifest_path.parent().unwrap_or(Path::new("release/current")).to_path_buf();
    if let Ok(text) = std::fs::read_to_string(&manifest_path) {
        if let Ok(v) = serde_json::from_str::<serde_json::Value>(&text) {
            let portable = v.get("portable")?.as_str()?.to_string();
            let exe = resolve_artifact(&current_dir, &portable);
            return Some(DesktopInfo {
                version: v.get("version")?.as_str()?.to_string(),
                commit: v.get("commit")?.as_str()?.to_string(),
                frontend_build_id: v.get("frontendBuildId")?.as_str().unwrap_or("").to_string(),
                web_build_id: v.get("webBuildId")?.as_str().unwrap_or("").to_string(),
                exe: exe.as_ref().map(|p| p.to_string_lossy().to_string()),
                exe_exists: exe.is_some(),
                manifest_ok: true,
            });
        }
    }
    let exe = portable_exe_fallback(root)?;
    let version = exe
        .file_name()
        .unwrap_or_default()
        .to_string_lossy()
        .trim_start_matches("Wildlife-Incident-Handoff-Portable-")
        .trim_end_matches(".exe")
        .to_string();
    Some(DesktopInfo {
        version,
        commit: String::new(),
        frontend_build_id: String::new(),
        web_build_id: String::new(),
        exe: Some(exe.to_string_lossy().to_string()),
        exe_exists: true,
        manifest_ok: false,
    })
}

#[tauri::command]
fn get_identity() -> Result<Identity, String> {
    let root = find_root().ok_or("Wildlife Incident Handoff workspace not found — place the launcher beside the project folder or inside it.")?;
    let version = read_version(&root).unwrap_or_else(|| "?".into());
    let commit = git(&root, &["rev-parse", "--short", "HEAD"]).unwrap_or_default();
    let is_git = git(&root, &["rev-parse", "--is-inside-work-tree"]).is_some();
    let dirty_inputs = dirty_build_inputs(&root);
    let git_dirty = !dirty_paths(&root).is_empty();
    let desktop = desktop_release(&root);

    let (freshness, detail) = if !is_git {
        (Freshness::NotGit, "Source is not a Git checkout — freshness cannot be verified.".into())
    } else if version != "?" && desktop.is_some() && desktop.as_ref().unwrap().manifest_ok && desktop.as_ref().unwrap().version != version {
        (Freshness::VersionMismatch, format!("Desktop is {} but source is {}.", desktop.as_ref().unwrap().version, version))
    } else if !dirty_inputs.is_empty() {
        (Freshness::SourceDirty, "Source has unbuilt changes.".into())
    } else if desktop.is_none() {
        (Freshness::DesktopMissing, "No packaged desktop build was found.".into())
    } else {
        let d = desktop.as_ref().unwrap();
        if !d.manifest_ok {
            (Freshness::SourceChanged, "Desktop identity manifest is missing — rebuild to restore verified freshness.".into())
        } else if d.commit == commit {
            (Freshness::Current, "Desktop build matches source.".into())
        } else {
            let changed = build_inputs_changed_between(&root, &d.commit, "HEAD");
            if changed.is_empty() {
                (Freshness::Current, "Desktop build matches source (newer commits touch no build inputs).".into())
            } else {
                (Freshness::SourceChanged, format!("Source changed since the desktop build ({} file(s)).", changed.len()))
            }
        }
    };

    let prev = desktop.as_ref().and_then(|d| previous_verified(&root, &d.version));
    Ok(Identity {
        root: root.to_string_lossy().to_string(),
        version,
        commit,
        git_dirty,
        dirty_build_inputs: dirty_inputs,
        desktop,
        previous: prev,
        freshness,
        freshness_detail: detail,
    })
}

fn launch_exe(path: &str) -> Result<String, String> {
    let p = PathBuf::from(path);
    if !p.is_file() {
        return Err(format!("Desktop executable not found: {}", path));
    }
    Command::new(&path)
        .creation_flags(CREATE_NO_WINDOW)
        .spawn()
        .map_err(|e| format!("failed to launch: {}", e))?;
    Ok(path.to_string())
}

#[tauri::command]
fn launch_app() -> Result<String, String> {
    let root = find_root().ok_or("workspace not found")?;
    let desktop = desktop_release(&root).ok_or("No packaged desktop build found. Use Build to create one.")?;
    let exe = desktop
        .exe
        .filter(|_| desktop.exe_exists)
        .ok_or_else(|| {
            format!(
                "Desktop executable for {} is missing from release/current. Use Build to create it.",
                desktop.version
            )
        })?;
    launch_exe(&exe)
}

#[tauri::command]
fn launch_previous() -> Result<String, String> {
    let root = find_root().ok_or("workspace not found")?;
    let identity_version = read_version(&root).unwrap_or_default();
    let prev = previous_verified(&root, &identity_version)
        .ok_or("No previous verified build was found in release/current.")?;
    launch_exe(&prev.exe)
}

#[tauri::command]
fn launch_web() -> Result<String, String> {
    let root = find_root().ok_or("workspace not found")?;
    // Web preview: vite dev server in a hidden console window; browser opens separately.
    Command::new("cmd")
        .args(["/C", "start", "", "http://localhost:5173/"])
        .creation_flags(CREATE_NO_WINDOW)
        .spawn()
        .ok();
    Command::new("cmd")
        .args(["/C", "npm", "run", "dev"])
        .current_dir(&root)
        .creation_flags(CREATE_NO_WINDOW)
        .spawn()
        .map_err(|e| format!("failed to start web preview: {}", e))?;
    Ok("http://localhost:5173/".into())
}

#[tauri::command]
fn build_app(state: State<'_, BuildState>) -> Result<(), String> {
    let root = find_root().ok_or("workspace not found")?;
    {
        let mut running = state.running.lock().unwrap();
        if *running {
            return Err("A build is already running.".into());
        }
        *running = true;
        *state.done.lock().unwrap() = None;
        state.lines.lock().unwrap().clear();
        // Stage 0 is visible the instant Build is clicked — before the child
        // process emits anything.
        *state.stage.lock().unwrap() = STAGES[0].to_string();
        *state.stage_index.lock().unwrap() = 0;
    }
    let state = state.inner().clone();
    std::thread::spawn(move || {
        let child = Command::new("cmd")
            .args(["/C", "npm", "run", "desktop:release"])
            .current_dir(&root)
            .creation_flags(CREATE_NO_WINDOW)
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped())
            .spawn();
        let ok = match child {
            Ok(mut c) => {
                use std::io::{BufRead, BufReader};
                let stdout = c.stdout.take().map(BufReader::new);
                let stderr = c.stderr.take().map(BufReader::new);
                let st2 = state.clone();
                let err_thread = std::thread::spawn(move || {
                    if let Some(mut r) = stderr {
                        let mut buf = String::new();
                        loop {
                            buf.clear();
                            match r.read_line(&mut buf) {
                                Ok(0) | Err(_) => break,
                                Ok(_) => {
                                    let mut lines = st2.lines.lock().unwrap();
                                    lines.push(buf.trim_end().to_string());
                                    if lines.len() > 800 {
                                        lines.drain(0..400);
                                    }
                                }
                            }
                        }
                    }
                });
                let st2 = state.clone();
                if let Some(mut r) = stdout {
                    let mut buf = String::new();
                    loop {
                        buf.clear();
                        match r.read_line(&mut buf) {
                            Ok(0) | Err(_) => break,
                            Ok(_) => {
                                let line = buf.trim_end().to_string();
                                if line.starts_with("=== ") {
                                    let step = line.trim_matches('=').trim();
                                    if let Some(i) = stage_for_step(step) {
                                        *st2.stage_index.lock().unwrap() = i;
                                        *st2.stage.lock().unwrap() = STAGES[i].to_string();
                                    }
                                }
                                let mut lines = st2.lines.lock().unwrap();
                                lines.push(line);
                                if lines.len() > 800 {
                                    lines.drain(0..400);
                                }
                            }
                        }
                    }
                }
                let status_ok = c.wait().map(|s| s.success()).unwrap_or(false);
                let _ = err_thread.join();
                status_ok
            }
            Err(e) => {
                state.lines.lock().unwrap().push(format!("build failed to start: {}", e));
                false
            }
        };
        let idx = if ok { STAGES.len() - 1 } else { 5 };
        *state.stage_index.lock().unwrap() = idx;
        *state.stage.lock().unwrap() = if ok { STAGES[STAGES.len() - 1].to_string() } else { "Build failed".into() };
        *state.done.lock().unwrap() = Some(ok);
        *state.last_ok.lock().unwrap() = Some(ok);
        *state.running.lock().unwrap() = false;
    });
    Ok(())
}

#[derive(Serialize, Clone)]
#[serde(rename_all = "camelCase")]
struct BuildStatus {
    running: bool,
    stage: String,
    stage_index: usize,
    stages: Vec<&'static str>,
    lines: Vec<String>,
    done: Option<bool>,
}

#[tauri::command]
fn get_build_status(state: State<BuildState>) -> BuildStatus {
    BuildStatus {
        running: *state.running.lock().unwrap(),
        stage: state.stage.lock().unwrap().clone(),
        stage_index: *state.stage_index.lock().unwrap(),
        stages: STAGES.to_vec(),
        lines: state.lines.lock().unwrap().iter().rev().take(14).rev().cloned().collect(),
        done: *state.done.lock().unwrap(),
    }
}

#[derive(Serialize, Clone)]
#[serde(rename_all = "camelCase")]
struct UpdateInfo {
    /// no-remote | offline | remote-error | auth | up-to-date | available | dirty-tree | error
    status: String,
    behind: u32,
    ahead: u32,
    local_commit: String,
    remote_commit: String,
    detail: String,
}

impl UpdateInfo {
    fn simple(status: &str, detail: &str) -> UpdateInfo {
        UpdateInfo {
            status: status.into(),
            behind: 0,
            ahead: 0,
            local_commit: String::new(),
            remote_commit: String::new(),
            detail: detail.into(),
        }
    }
}

/// Read-only update check: never pulls, never overwrites local work.
#[tauri::command]
fn check_updates() -> UpdateInfo {
    let root = match find_root() {
        Some(r) => r,
        None => return UpdateInfo::simple("error", "Workspace not found."),
    };
    let local = git(&root, &["rev-parse", "--short", "HEAD"]).unwrap_or_default();

    // 1. Is a remote even configured?
    let remotes = git(&root, &["remote"]).unwrap_or_default();
    if remotes.is_empty() {
        return UpdateInfo::simple(
            "no-remote",
            "No Git remote is configured for this source checkout.",
        );
    }
    let remote_name = remotes.lines().next().unwrap_or("origin").to_string();

    // 2. Can we reach it? Distinguish offline vs auth vs other failure.
    let fetched = git(&root, &["fetch", &remote_name, "--quiet"]).is_some();
    let fetch_err = if fetched {
        String::new()
    } else {
        // Re-run quietly to capture a human-readable reason.
        let out = Command::new("git")
            .args(["fetch", &remote_name])
            .current_dir(&root)
            .creation_flags(CREATE_NO_WINDOW)
            .output();
        match out {
            Ok(o) => {
                let e = String::from_utf8_lossy(&o.stderr).to_lowercase();
                if e.contains("could not resolve host") || e.contains("timed out") || e.contains("connection") || e.contains("network") || e.contains("unable to access") {
                    "offline".into()
                } else if e.contains("authentication") || e.contains("could not read username") || e.contains("permission") || e.contains("403") {
                    "auth".into()
                } else {
                    "remote-error".into()
                }
            }
            Err(_) => "remote-error".into(),
        }
    };
    if !fetched {
        return match fetch_err.as_str() {
            "offline" => UpdateInfo::simple(
                "offline",
                "You're offline. Update checking will be available when a connection returns.",
            ),
            "auth" => UpdateInfo::simple(
                "auth",
                "Update check requires repository access (authentication failed).",
            ),
            other => UpdateInfo {
                status: "remote-error".into(),
                behind: 0,
                ahead: 0,
                local_commit: local.clone(),
                remote_commit: String::new(),
                detail: format!("Couldn't check for updates ({}).", other),
            },
        };
    }

    // 3. Compare with the remote's main branch.
    let remote_branch = format!("{}/main", remote_name);
    if git(&root, &["rev-parse", "--verify", &remote_branch]).is_none() {
        let remote_branch_alt = format!("{}/master", remote_name);
        if git(&root, &["rev-parse", "--verify", &remote_branch_alt]).is_none() {
            return UpdateInfo::simple(
                "remote-error",
                "The remote has no main/master branch to compare against.",
            );
        }
        return compare_remote(&root, &remote_branch_alt, local);
    }
    compare_remote(&root, &remote_branch, local)
}

fn compare_remote(root: &Path, remote_branch: &str, local: String) -> UpdateInfo {
    let behind = git(root, &["rev-list", "--count", &format!("HEAD..{}", remote_branch)])
        .and_then(|s| s.parse::<u32>().ok())
        .unwrap_or(0);
    let ahead = git(root, &["rev-list", "--count", &format!("{}..HEAD", remote_branch)])
        .and_then(|s| s.parse::<u32>().ok())
        .unwrap_or(0);
    let remote_commit = git(root, &["rev-parse", "--short", remote_branch]).unwrap_or_default();
    if behind > 0 {
        UpdateInfo {
            status: "available".into(),
            behind,
            ahead,
            local_commit: local,
            remote_commit,
            detail: format!(
                "Source update available: {} commit(s) on {}. The launcher never pulls over your working tree.",
                behind, remote_branch
            ),
        }
    } else {
        UpdateInfo {
            status: "up-to-date".into(),
            behind: 0,
            ahead,
            local_commit: local,
            remote_commit,
            detail: "You're up to date.".into(),
        }
    }
}

const THEME_FILE: &str = "launcher-theme.json";

fn dirs_config() -> Option<PathBuf> {
    // Shared with the main app's data dir (org.wildlifeincidenthandoff.app).
    let appdata = std::env::var("APPDATA").ok()?;
    Some(PathBuf::from(appdata).join("org.wildlifeincidenthandoff.app"))
}

fn theme_path() -> Option<PathBuf> {
    Some(dirs_config()?.join(THEME_FILE))
}

#[derive(Serialize, Clone)]
#[derive(Deserialize)]
struct VisualPref {
    theme: String,
    motion: String,
    material: String,
}

impl Default for VisualPref {
    fn default() -> Self {
        // Fresh user: Forest Night.
        VisualPref { theme: "forest-night".into(), motion: "full".into(), material: "frosted".into() }
    }
}

#[tauri::command]
fn get_theme() -> VisualPref {
    if let Some(p) = theme_path() {
        if let Ok(text) = std::fs::read_to_string(p) {
            if let Ok(v) = serde_json::from_str::<VisualPref>(&text) {
                return v;
            }
        }
    }
    VisualPref::default()
}

#[tauri::command]
fn set_theme(theme: String) -> Result<(), String> {
    let p = theme_path().ok_or("no config dir")?;
    if let Some(dir) = p.parent() {
        std::fs::create_dir_all(dir).map_err(|e| e.to_string())?;
    }
    let mut pref = VisualPref::default();
    if let Ok(text) = std::fs::read_to_string(&p) {
        if let Ok(v) = serde_json::from_str::<VisualPref>(&text) {
            pref = v;
        }
    }
    pref.theme = theme;
    std::fs::write(&p, serde_json::to_string(&pref).map_err(|e| e.to_string())?).map_err(|e| e.to_string())
}

#[derive(Serialize, Clone)]
#[serde(rename_all = "camelCase")]
struct Diagnostics {
    launcher_version: String,
    source_version: String,
    source_commit: String,
    git_dirty: bool,
    dirty_files: Vec<String>,
    desktop_version: String,
    desktop_commit: String,
    desktop_path: String,
    web_build_id: String,
    release_current_path: String,
    git_remote: String,
    last_build_result: String,
}

#[tauri::command]
fn get_diagnostics(state: State<'_, BuildState>) -> Result<Diagnostics, String> {
    let identity = get_identity()?;
    let root = PathBuf::from(&identity.root);
    let d = identity.desktop.clone().unwrap_or(DesktopInfo {
        version: "—".into(),
        commit: "—".into(),
        frontend_build_id: String::new(),
        web_build_id: String::new(),
        exe: None,
        exe_exists: false,
        manifest_ok: false,
    });
    Ok(Diagnostics {
        launcher_version: env!("CARGO_PKG_VERSION").to_string(),
        source_version: identity.version.clone(),
        source_commit: identity.commit.clone(),
        git_dirty: identity.git_dirty,
        dirty_files: dirty_paths(&root),
        desktop_version: d.version.clone(),
        desktop_commit: d.commit.clone(),
        desktop_path: d.exe.clone().unwrap_or_else(|| "not found".into()),
        web_build_id: d.web_build_id.clone(),
        release_current_path: root.join("release").join("current").to_string_lossy().to_string(),
        git_remote: git(&root, &["remote", "-v"]).unwrap_or_else(|| "none configured".into()),
        last_build_result: match (*state.last_ok.lock().unwrap()).clone() {
            Some(true) => "last build: success".into(),
            Some(false) => "last build: FAILED".into(),
            None => "no build run this session".into(),
        },
    })
}


// ---------- RC2: launcher preferences + release-channel update check ----------

#[derive(Serialize, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
struct Prefs {
    theme: String,
    motion: String,
    material: String,
    channel: String,
    auto_check_updates: bool,
    dev_tools_visible: bool,
}

impl Default for Prefs {
    fn default() -> Self {
        Prefs {
            theme: "forest-night".into(),
            motion: "full".into(),
            material: "frosted".into(),
            channel: "tester".into(),
            auto_check_updates: true,
            dev_tools_visible: true,
        }
    }
}

fn prefs_file() -> Option<PathBuf> {
    let appdata = std::env::var("APPDATA").ok()?;
    Some(PathBuf::from(appdata).join("org.wildlifeincidenthandoff.app").join("launcher-prefs.json"))
}

#[tauri::command]
fn get_prefs() -> Prefs {
    if let Some(p) = prefs_file() {
        if let Ok(text) = std::fs::read_to_string(p) {
            if let Ok(v) = serde_json::from_str::<Prefs>(&text) {
                return v;
            }
        }
    }
    Prefs::default()
}

#[tauri::command]
fn set_prefs(prefs: Prefs) -> Result<(), String> {
    let p = prefs_file().ok_or("no config dir")?;
    if let Some(dir) = p.parent() {
        std::fs::create_dir_all(dir).map_err(|e| e.to_string())?;
    }
    // Keep the legacy theme-sync file in step so the app + launcher stay aligned.
    let _ = std::fs::write(
        p.parent().unwrap().join("launcher-theme.json"),
        serde_json::json!({"theme": prefs.theme, "motion": prefs.motion, "material": prefs.material}).to_string(),
    );
    std::fs::write(&p, serde_json::to_string(&prefs).map_err(|e| e.to_string())?).map_err(|e| e.to_string())
}

#[derive(Serialize, Clone)]
#[serde(rename_all = "camelCase")]
struct ReleaseCheck {
    status: String, // up-to-date | available | offline | unavailable | error
    channel: String,
    current_version: String,
    latest_version: Option<String>,
    notes_url: Option<String>,
    detail: String,
}

/// Check the installed Workbench version against the GitHub release channel
/// metadata (latest.json for stable, tester.json for the RC channel).
/// Read-only: the launcher never downloads or installs binaries itself.
#[tauri::command]
fn check_release_update(channel: String) -> ReleaseCheck {
    let current = desktop_release(&find_root().unwrap_or_default())
        .map(|d| d.version)
        .unwrap_or_else(|| read_version(&find_root().unwrap_or_default()).unwrap_or_default());
    let endpoint = if channel == "stable" {
        "https://github.com/amgedi/Wildlife-Incident-Handoff/releases/latest/download/latest.json"
    } else {
        "https://github.com/amgedi/Wildlife-Incident-Handoff/releases/latest/download/tester.json"
    };
    let resp = ureq::get(endpoint).timeout(std::time::Duration::from_secs(12)).call();
    match resp {
        Ok(r) => match r.into_json::<serde_json::Value>() {
            Ok(v) => {
                let latest = v.get("version").and_then(|x| x.as_str()).map(String::from);
                let notes = v.get("notes").and_then(|x| x.as_str()).map(String::from);
                let newer = match (&latest, semver_like(&current)) {
                    (Some(l), Some(c)) => semver_like(l).map(|ln| ln > c).unwrap_or(false),
                    _ => latest.is_some() && latest.as_deref() != Some(current.as_str()),
                };
                if newer {
                    let ch = channel.clone();
                    let cur = current.clone();
                    ReleaseCheck {
                        status: "available".into(),
                        channel: ch,
                        current_version: current,
                        latest_version: latest.clone(),
                        notes_url: Some(format!(
                            "https://github.com/amgedi/Wildlife-Incident-Handoff/releases/tag/v{}",
                            latest.clone().unwrap_or_default()
                        )),
                        detail: format!("Wildlife Incident Handoff {} is available on the {} channel.", latest.clone().unwrap_or_default(), channel.clone()),
                    }
                } else {
                    ReleaseCheck {
                        status: "up-to-date".into(),
                        channel: channel.clone(),
                        current_version: current.clone(),
                        latest_version: latest,
                        notes_url: None,
                        detail: format!("Installed version {} is current on the {} channel.", current, channel),
                    }
                }
            }
            Err(e) => ReleaseCheck {
                status: "unavailable".into(), channel: channel.clone(), current_version: current.clone(),
                latest_version: None, notes_url: None,
                detail: format!("Release metadata could not be parsed ({}). The repository may not be published yet.", e),
            },
        },
        Err(e) => {
            let offline = e.to_string().to_lowercase().contains("connection")
                || e.to_string().to_lowercase().contains("dns")
                || e.to_string().to_lowercase().contains("timed");
            ReleaseCheck {
                status: if offline { "offline".into() } else { "unavailable".into() },
                channel, current_version: current.clone(), latest_version: None, notes_url: None,
                detail: if offline {
                    "You're offline. Update checking resumes when a connection returns.".into()
                } else {
                    "The release service could not be reached. The public repository may not be published yet.".into()
                },
            }
        }
    }
}

/// Minimal "major.minor.patch[-rc.N]" comparison helper (no external semver dep).
fn semver_like(v: &str) -> Option<(u64, u64, u64, u64)> {
    let core = v.trim_start_matches('v');
    let (nums, pre) = match core.split_once('-') {
        Some((n, p)) => (n, p),
        None => (core, ""),
    };
    let mut it = nums.split('.');
    let maj: u64 = it.next()?.parse().ok()?;
    let min: u64 = it.next()?.parse().ok()?;
    let pat: u64 = it.next()?.parse().ok()?;
    let rc = if let Some(n) = pre.strip_prefix("rc.") { n.parse().unwrap_or(0) } else { u64::MAX };
    Some((maj, min, pat, rc))
}

#[tauri::command]
fn open_release_folder() -> Result<(), String> {
    let root = find_root().ok_or("workspace not found")?;
    let dir = root.join("release").join("current");
    Command::new("explorer").arg(&dir).creation_flags(CREATE_NO_WINDOW).spawn().map(|_| ()).map_err(|e| e.to_string())
}

#[tauri::command]
fn open_logs_folder() -> Result<(), String> {
    let appdata = std::env::var("APPDATA").map_err(|_| "no APPDATA")?;
    let dir = PathBuf::from(appdata).join("org.wildlifeincidenthandoff.app");
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    Command::new("explorer").arg(&dir).creation_flags(CREATE_NO_WINDOW).spawn().map(|_| ()).map_err(|e| e.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stage_mapping_covers_pipeline_steps() {
        assert_eq!(stage_for_step("=== tests ==="), Some(1));
        assert_eq!(stage_for_step("=== build frontend (prebuild generates build identity) ==="), Some(2));
        assert_eq!(stage_for_step("=== build Tauri desktop ==="), Some(3));
        assert_eq!(stage_for_step("=== package release artifacts ==="), Some(4));
        assert_eq!(stage_for_step("=== verify version parity + build identity ==="), Some(5));
        assert_eq!(stage_for_step("=== release manifest ==="), Some(6));
        assert_eq!(stage_for_step("=== checksums ==="), Some(6));
        assert_eq!(stage_for_step("=== clean stale frontend artifacts ==="), Some(0));
        assert_eq!(stage_for_step("=== something unknown ==="), None);
    }

    #[test]
    fn artifact_resolution_joins_manifest_directory() {
        // Root cause of the dev.6 "Desktop executable not found" failure: bare
        // manifest filenames must resolve relative to the manifest's directory.
        let dir = std::env::temp_dir().join("wih-launcher-test-current");
        std::fs::create_dir_all(&dir).unwrap();
        let exe = dir.join("Wildlife-Incident-Handoff-Portable-0.3.0-dev.7.exe");
        std::fs::write(&exe, b"MZ").unwrap();
        let resolved = resolve_artifact(&dir, "Wildlife-Incident-Handoff-Portable-0.3.0-dev.7.exe");
        assert_eq!(resolved, Some(exe.clone()));
        assert_eq!(resolve_artifact(&dir, "does-not-exist.exe"), None);
        let _ = std::fs::remove_file(&exe);
    }

    #[test]
    fn dirty_filter_excludes_generated_build_identity() {
        let raw = " M src/build-identity.ts\n M src/App.tsx\n?? docs/notes.md\n";
        let paths: Vec<String> = raw
            .lines()
            .filter_map(|l| if l.len() < 4 { None } else { Some(l[3..].trim().trim_matches('"').replace('\\', "/")) })
            .filter(|p| BUILD_INPUTS.iter().any(|b| p == *b || p.starts_with(&format!("{}/", *b))))
            .filter(|p| !GENERATED_DIRTY_EXEMPT.iter().any(|g| p == *g || p.starts_with(&format!("{}/", *g))))
            .collect();
        // Only the real code change counts; the generated identity file is exempt.
        assert_eq!(paths, vec!["src/App.tsx".to_string()]);
    }

    #[test]
    fn freshness_inputs_ignore_docs_but_not_source() {
        let diff = "docs/REPORT.md\nscreenshots/a.png\nsrc/build-identity.ts\n";
        let changed: Vec<String> = diff
            .lines()
            .map(|p| p.replace('\\', "/"))
            .filter(|p| BUILD_INPUTS.iter().any(|b| p == *b || p.starts_with(&format!("{}/", *b))))
            .filter(|p| !GENERATED_DIRTY_EXEMPT.iter().any(|g| p == *g || p.starts_with(&format!("{}/", *g))))
            .collect();
        // A release/chore commit touching only docs + generated identity does
        // NOT make the packaged build stale (dev.6 false-"Out of date" fix).
        assert!(changed.is_empty());
    }
}
