/** Build identity — generated by scripts/gen-build-identity.mjs at build time.
 *  DO NOT EDIT BY HAND. Surfaces in Settings → About so a stale/crossed build
 *  is immediately diagnosable (0.3.0-dev.4 spec 1, 48). */
export const BUILD_COMMIT = "6654355";
export const BUILD_TIME = "2026-10-04 22:17";
export const FRONTEND_BUILD_ID = "32361dcaf1e2";
